"""add documents.content_sha256 for ingestion dedup

Revision ID: 31c00c3e4441
Revises: f140fceba154
Create Date: 2026-05-21 12:25:49.064026

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '31c00c3e4441'
down_revision: str | None = 'f140fceba154'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents",
        sa.Column("content_sha256", sa.String(length=64), nullable=True),
    )
    op.create_index(
        op.f("ix_documents_content_sha256"),
        "documents",
        ["content_sha256"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_content_sha256'), table_name='documents')
    op.drop_column('documents', 'content_sha256')
    # ### end Alembic commands ###
