"""add document_chunks page_start page_end for citations

Revision ID: 96be68f88a51
Revises: 31c00c3e4441
Create Date: 2026-05-21 16:25:07.894579

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '96be68f88a51'
down_revision: str | None = '31c00c3e4441'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'document_chunks', sa.Column('page_start', sa.Integer(), nullable=True)
    )
    op.add_column(
        'document_chunks', sa.Column('page_end', sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'page_end')
    op.drop_column('document_chunks', 'page_start')
    # ### end Alembic commands ###
